### ISSUE TITLE
emergency calls only on SM A500H

### ISSUE THREAD

**Issue by nonsocchi** [DeadSquirrel01/android_device_samsung_a5-common#6] opened 2016-12-31 04:25 UTC
It shows sim card not detected.  Pls how can I fix this. Is there a patch I can flash?

**Comment by DeadSquirrel01** [comment] 2016-12-31 08:43
Have you copied /system/lib/libsecril.so from stock ROM? This is shown in instructions. Please read them before posting bugs. If it still doesn't work please reply

**Comment by DeadSquirrel01** [comment] 2016-12-31 10:24
Well, you reported it in bug section, while it is not a bug. These things should ne asked in help sections like the thread or on IRC. So, I think I can close it now

**Closed as completed by DeadSquirrel01** 2016-12-31 10:24 UTC

**Comment by RemonAbdelmalak** [comment] 2017-03-24 19:12
I cant find libsecril.so
It only shows libsecril-client.so 
Is that is ?!

**Comment by nonsocchi** [comment] 2017-03-27 07:00
No. Those are 2 separate files. Take a look at this.
