### ISSUE TITLE
Camera, AudioFX

### ISSUE THREAD

**Issue by ProManiFest** [DeadSquirrel01/android_device_samsung_a5-common#2] opened 2016-10-15 00:23 UTC
When i start filming immediately turns off. 
I do not know if this is bug, but AudioFX doesn't work. You can check this
I go looking for more bugs

**Comment by DeadSquirrel01** [comment] 2016-10-15 21:47
Strange, AUDIOFX and camera both works, have you formatted data/cache/dalvik before flashing?

**Comment by ProManiFest** [comment] 2016-10-16 10:26
I'll see maybe it's my fault

**Comment by ProManiFest** [comment] 2016-10-17 14:46
Okey, I installed again system with yours modem and BL and AudioFX working, but i can't making videos i can only take photos

**Comment by DeadSquirrel01** [comment] 2016-10-17 15:08
With can't record video bug, i agree :D

**Comment by ProManiFest** [comment] 2016-10-17 16:12
The buttons below the screen react when phone be blocked

**Comment by ProManiFest** [comment] 2016-10-17 16:13
or my phone have ADHD xdd

**Comment by DeadSquirrel01** [comment] 2016-10-20 19:28
That's not a bug

**Comment by nonsocchi** [comment] 2016-12-31 04:22
I'm having the same problem. I can't record videos and sound doesn't work on my phone. Also, my sim card doesn't work either.

**Comment by DeadSquirrel01** [comment] 2017-02-18 17:31
AudioFX was working.
Camera that couldn't take videos is fixed with https://github.com/DeadSquirrel01/android_device_samsung_a5-common/commit/b648ca1e66bdd9a00c3d46e81ca07b6233f72a9a
I can close this now

**Closed as completed by DeadSquirrel01** 2017-02-18 17:31 UTC
