### ISSUE TITLE
In-call audio, buttons

### ISSUE THREAD

**Issue by ProManiFest** [DeadSquirrel01/android_device_samsung_a5-common#1] opened 2016-10-14 10:54 UTC
Hi, 
When the phone is locked buttons under the screen ( back and recent) for 2-3 seconds still work and in-call audio doesn't work. Sorry for ma English ;)

**Comment by ProManiFest** [comment] 2016-10-14 23:40
When i start filming immediately turns off. 
I do not know if this is bug, but AudioFX doesn't work. You can check this
I go looking for more bugs

**Comment by DeadSquirrel01** [comment] 2016-10-15 21:48
Yes, audio call doesn't work, tested by myself ^^, i have to fix in next builds :D

**Comment by gadLinux** [comment] 2016-12-05 15:57
Yes I can confirm. But's curious that signalmeter reads microphone just right.
It will be great if you can add this patch. Since the mobile is unusable without it. 

I can test the rest while using it if you patch it soon. Otherwise I will have to use other image since I use the mobile a lot for calling.

**Comment by knuxify** [comment] 2017-08-03 07:48
I know this is an old thread but I would like to note that a simmilar button problem has been described here: [link to the issue](https://github.com/DeadSquirrel01/android_device_samsung_a5-common/issues/7), and a simmilar in-call audio bug is described here: [link to the issue](https://github.com/DeadSquirrel01/android_device_samsung_a5-common/issues/10)

**Comment by DeadSquirrel01** [comment] 2017-09-14 21:08
Fixed with https://github.com/DeadSquirrel01/android_device_samsung_a5-common/commit/83bb8f906922d695798bb8ab4b2df1333c757a58

**Closed as completed by DeadSquirrel01** 2017-09-14 21:08 UTC
